In [4]:
import numpy as np

Concatenación de filas

In [5]:
classroom_ids_and_sizes = np.array([[1, 22], 
                                    [2, 21], 
                                    [3, 27], 
                                    [4, 26]]) 
new_classrooms = np.array([[5, 30], 
                           [5, 17]])  
np.concatenate((classroom_ids_and_sizes, new_classrooms))

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26],
       [ 5, 30],
       [ 5, 17]])

Concatenación de columnas

In [6]:
classroom_ids_and_sizes = np.array([[1, 22], 
                                    [2, 21], 
                                    [3, 27], 
                                    [4, 26]]) 
grade_levels_and_teachers = np.array([[1, "James"], 
                                      [1, "George"], 
                                      [3,"Amy"], 
                                      [3, "Meehir"]]) 
np.concatenate((classroom_ids_and_sizes, grade_levels_and_teachers), axis=1)

array([['1', '22', '1', 'James'],
       ['2', '21', '1', 'George'],
       ['3', '27', '3', 'Amy'],
       ['4', '26', '3', 'Meehir']], dtype='<U21')

Creación de compatibilidad

In [7]:
array_1D = np.array([1, 2, 3]) 
column_array_2D = array_1D.reshape((3, 1)) 
column_array_2D 

array([[1],
       [2],
       [3]])

In [8]:
row_array_2D = array_1D.reshape((1, 3)) 
row_array_2D 

array([[1, 2, 3]])

Eliminar con np.delete()

In [13]:
classroom_data=np.array([[1, 22, 1, 'James'],
                        [2, 21, 1, 'George'],
                        [3, 27, 3, 'Amy'],
                        [4, 26, 3, 'Meehir']],)
classroom_data

array([['1', '22', '1', 'James'],
       ['2', '21', '1', 'George'],
       ['3', '27', '3', 'Amy'],
       ['4', '26', '3', 'Meehir']], dtype='<U21')

In [11]:
np.delete(classroom_data,1,axis=0)

array([['1', '22', '1', 'James'],
       ['3', '27', '3', 'Amy'],
       ['4', '26', '3', 'Meehir']], dtype='<U21')

Eliminación de columnas

In [12]:
np.delete(classroom_data, 1, axis=1)

array([['1', '1', 'James'],
       ['2', '1', 'George'],
       ['3', '3', 'Amy'],
       ['4', '3', 'Meehir']], dtype='<U21')

Eliminación sin eje

In [14]:
np.delete(classroom_data, 1)

array(['1', '1', 'James', '2', '21', '1', 'George', '3', '27', '3', 'Amy',
       '4', '26', '3', 'Meehir'], dtype='<U21')