In [11]:
import numpy as np

3D arrays


In [12]:
array_1_2D = np.array([[1,2],[5,7]])
array_2_2D = np.array([[8,9],[5,7]])
array_3_2D = np.array([[1,2],[5,7]])
array_3D = np.array([array_1_2D,array_2_2D,array_3_2D])
array_3D

array([[[1, 2],
        [5, 7]],

       [[8, 9],
        [5, 7]],

       [[1, 2],
        [5, 7]]])

4D arrays

In [13]:
array_A1_2D = np.random.randint(0, 10, size=(2, 2))
array_A2_2D = np.random.randint(0, 10, size=(2, 2))
array_A3_2D = np.random.randint(0, 10, size=(2, 2))
array_A_3D = np.array([array_A1_2D,array_A2_2D,array_A3_2D])
array_B1_2D = np.random.randint(0, 10, size=(2, 2))
array_B2_2D = np.random.randint(0, 10, size=(2, 2))
array_B3_2D = np.random.randint(0, 10, size=(2, 2))
array_B_3D = np.array([array_B1_2D,array_B2_2D,array_B3_2D])
array_C1_2D = np.random.randint(0, 10, size=(2, 2))
array_C2_2D = np.random.randint(0, 10, size=(2, 2))
array_C3_2D = np.random.randint(0, 10, size=(2, 2))
array_C_3D = np.array([array_C1_2D,array_C2_2D,array_C3_2D])
array_D1_2D = np.random.randint(0, 10, size=(2, 2))
array_D2_2D = np.random.randint(0, 10, size=(2, 2))
array_D3_2D = np.random.randint(0, 10, size=(2, 2))
array_D_3D = np.array([array_D1_2D,array_D2_2D,array_D3_2D])
array_E1_2D = np.random.randint(0, 10, size=(2, 2))
array_E2_2D = np.random.randint(0, 10, size=(2, 2))
array_E3_2D = np.random.randint(0, 10, size=(2, 2))
array_E_3D = np.array([array_E1_2D,array_E2_2D,array_E3_2D])
array_F1_2D = np.random.randint(0, 10, size=(2, 2))
array_F2_2D = np.random.randint(0, 10, size=(2, 2))
array_F3_2D = np.random.randint(0, 10, size=(2, 2))
array_F_3D = np.array([array_F1_2D,array_F2_2D,array_F3_2D])
array_G1_2D = np.random.randint(0, 10, size=(2, 2))
array_G2_2D = np.random.randint(0, 10, size=(2, 2))
array_G3_2D = np.random.randint(0, 10, size=(2, 2))
array_G_3D = np.array([array_G1_2D,array_G2_2D,array_G3_2D])
array_H1_2D = np.random.randint(0, 10, size=(2, 2))
array_H2_2D = np.random.randint(0, 10, size=(2, 2))
array_H3_2D = np.random.randint(0, 10, size=(2, 2))
array_H_3D = np.array([array_H1_2D,array_H2_2D,array_H3_2D])
array_I1_2D = np.random.randint(0, 10, size=(2, 2))
array_I2_2D = np.random.randint(0, 10, size=(2, 2))
array_I3_2D = np.random.randint(0, 10, size=(2, 2))
array_I_3D = np.array([array_I1_2D,array_I2_2D,array_I3_2D])
array_4D = np.array([array_A_3D, array_B_3D, array_C_3D, array_D_3D, array_E_3D, array_F_3D, array_G_3D, array_H_3D, array_I_3D])
array_4D


array([[[[5, 2],
         [8, 3]],

        [[5, 1],
         [2, 0]],

        [[0, 3],
         [2, 5]]],


       [[[2, 0],
         [0, 3]],

        [[9, 0],
         [8, 8]],

        [[6, 5],
         [3, 7]]],


       [[[6, 5],
         [3, 2]],

        [[2, 2],
         [5, 3]],

        [[0, 9],
         [3, 7]]],


       [[[8, 1],
         [2, 4]],

        [[2, 7],
         [7, 0]],

        [[7, 0],
         [5, 7]]],


       [[[5, 2],
         [6, 8]],

        [[2, 3],
         [2, 7]],

        [[5, 8],
         [9, 1]]],


       [[[1, 0],
         [9, 4]],

        [[5, 1],
         [8, 6]],

        [[0, 0],
         [7, 2]]],


       [[[1, 5],
         [9, 0]],

        [[4, 3],
         [8, 9]],

        [[4, 4],
         [6, 7]]],


       [[[7, 4],
         [6, 4]],

        [[8, 5],
         [4, 2]],

        [[6, 9],
         [1, 4]]],


       [[[2, 5],
         [2, 1]],

        [[0, 9],
         [6, 5]],

        [[9, 3],
         [3, 0]]]], dtype=int32

In [14]:
array_A_3D=np.random.randint(0, 10, size=(3, 2, 2))
array_B_3D=np.random.randint(0, 10, size=(3, 2, 2))
array_C_3D=np.random.randint(0, 10, size=(3, 2, 2))
array_D_3D=np.random.randint(0, 10, size=(3, 2, 2))
array_E_3D=np.random.randint(0, 10, size=(3, 2, 2))
array_F_3D=np.random.randint(0, 10, size=(3, 2, 2))
array_G_3D=np.random.randint(0, 10, size=(3, 2, 2))
array_H_3D=np.random.randint(0, 10, size=(3, 2, 2))
array_I_3D=np.random.randint(0, 10, size=(3, 2, 2))
array_4D = np.array([array_A_3D, array_B_3D, array_C_3D, array_D_3D, array_E_3D, array_F_3D, array_G_3D, array_H_3D, array_I_3D])
array_4D

array([[[[1, 8],
         [5, 3]],

        [[9, 8],
         [1, 4]],

        [[5, 6],
         [6, 8]]],


       [[[2, 8],
         [5, 0]],

        [[4, 4],
         [0, 8]],

        [[4, 2],
         [5, 4]]],


       [[[1, 5],
         [1, 5]],

        [[8, 3],
         [5, 9]],

        [[5, 4],
         [7, 2]]],


       [[[9, 5],
         [0, 1]],

        [[8, 6],
         [3, 6]],

        [[4, 7],
         [6, 5]]],


       [[[2, 5],
         [3, 5]],

        [[3, 9],
         [9, 4]],

        [[2, 7],
         [6, 8]]],


       [[[7, 9],
         [4, 2]],

        [[6, 2],
         [7, 8]],

        [[7, 7],
         [6, 7]]],


       [[[5, 1],
         [8, 1]],

        [[4, 5],
         [9, 0]],

        [[4, 8],
         [5, 9]]],


       [[[9, 7],
         [9, 9]],

        [[8, 3],
         [6, 7]],

        [[6, 5],
         [9, 6]]],


       [[[8, 6],
         [7, 6]],

        [[6, 0],
         [6, 2]],

        [[2, 2],
         [2, 4]]]], dtype=int32

In [15]:
array_4D=np.random.randint(0, 10, size=(9, 3, 2, 2))
array_4D

array([[[[7, 0],
         [3, 5]],

        [[2, 2],
         [3, 8]],

        [[7, 4],
         [3, 8]]],


       [[[2, 7],
         [0, 5]],

        [[5, 0],
         [0, 9]],

        [[1, 4],
         [3, 3]]],


       [[[2, 7],
         [0, 2]],

        [[0, 2],
         [2, 2]],

        [[5, 5],
         [2, 4]]],


       [[[8, 7],
         [4, 3]],

        [[7, 3],
         [4, 8]],

        [[1, 6],
         [5, 3]]],


       [[[3, 9],
         [4, 0]],

        [[6, 1],
         [3, 1]],

        [[7, 8],
         [2, 8]]],


       [[[3, 0],
         [4, 5]],

        [[2, 0],
         [8, 4]],

        [[3, 6],
         [1, 8]]],


       [[[8, 1],
         [2, 0]],

        [[8, 7],
         [3, 4]],

        [[3, 6],
         [2, 4]]],


       [[[9, 9],
         [2, 3]],

        [[2, 7],
         [8, 3]],

        [[1, 2],
         [3, 7]]],


       [[[0, 3],
         [1, 2]],

        [[9, 2],
         [6, 0]],

        [[3, 3],
         [4, 2]]]], dtype=int32

Encontrar la forma de una matriz

In [16]:
array=np.zeros((3,5))
print(array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
array.shape

(3, 5)

Flattening un array


In [18]:
array = np.array([[1, 2], [5, 7], [6, 6]]) 
array.flatten()

array([1, 2, 5, 7, 6, 6])

Remodelación de una matriz

In [19]:
array = np.array([[1, 2], [5, 7], [6, 6]]) 
array.reshape((2, 3))

array([[1, 2, 5],
       [7, 6, 6]])

In [20]:
array.reshape((3, 3)) #No se puede cambiar la cantidad de datos


ValueError: cannot reshape array of size 6 into shape (3,3)