In [21]:
import numpy as np

Indexación de matrices 1D

In [22]:
array = np.array([2, 4, 6, 8, 10]) 
print(array[3])

8


Indexación de elementos en 2D

In [23]:
sudoku_game=np.array([[0,0,4,3,0,0,2,0,9],
                      [0,0,5,0,0,9,0,0,1],
                      [0,7,0,0,6,0,0,4,3],
                      [0,0,6,0,0,2,0,8,7],
                      [1,9,0,0,0,7,4,0,0],
                      [0,5,0,0,8,3,0,0,0],
                      [6,0,0,0,0,1,1,0,5],
                      [0,0,3,5,0,8,6,9,0],
                      [0,4,2,9,1,0,3,0,0]])
print(sudoku_game[2,4])

6


In [24]:
sudoku_game[0]

array([0, 0, 4, 3, 0, 0, 2, 0, 9])

In [25]:
sudoku_game[:,3]

array([3, 0, 0, 0, 0, 0, 0, 5, 9])

Segmentación de matrices 1D

In [26]:
array = np.array([2, 4, 6, 8, 10]) 
array[2:4]

array([6, 8])

Segmentación de matrices 2D

In [27]:
sudoku_game[3:6, 3:6]

array([[0, 0, 2],
       [0, 0, 7],
       [0, 8, 3]])

Cortar de forma escalonada

In [28]:
sudoku_game[3:6:2, 3:6:2]

array([[0, 2],
       [0, 3]])

Sorting arrays

In [29]:
np.sort(sudoku_game) 

array([[0, 0, 0, 0, 0, 2, 3, 4, 9],
       [0, 0, 0, 0, 0, 0, 1, 5, 9],
       [0, 0, 0, 0, 0, 3, 4, 6, 7],
       [0, 0, 0, 0, 0, 2, 6, 7, 8],
       [0, 0, 0, 0, 0, 1, 4, 7, 9],
       [0, 0, 0, 0, 0, 0, 3, 5, 8],
       [0, 0, 0, 0, 0, 1, 1, 5, 6],
       [0, 0, 0, 0, 3, 5, 6, 8, 9],
       [0, 0, 0, 0, 1, 2, 3, 4, 9]])

Sorting by axis

In [30]:
np.sort(sudoku_game, axis=0) 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0, 2, 1, 0, 1],
       [0, 4, 3, 0, 0, 3, 2, 0, 3],
       [0, 5, 4, 3, 1, 7, 3, 4, 5],
       [1, 7, 5, 5, 6, 8, 4, 8, 7],
       [6, 9, 6, 9, 8, 9, 6, 9, 9]])