In [1]:
import numpy as np

Operaciones vectorizadas

In [3]:
print(np.arange(1000000).sum())

499999500000


Velocidad en comparación con Python

In [9]:
array = np.array([[1, 2, 3], [4, 5, 6]]) 
for row in range(array.shape[0]): 
    for column in range(array.shape[1]): 
        array[row][column] += 3
array

array([[4, 5, 6],
       [7, 8, 9]])

NumPy sintaxis

In [10]:
array = np.array([[1, 2, 3], [4, 5, 6]]) 
array + 3 

array([[4, 5, 6],
       [7, 8, 9]])

Multiplicación por un escalar

In [11]:
array = np.array([[1, 2, 3], [4, 5, 6]]) 
array * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

Sumatoria de dos matrices juntas

In [12]:
array_a = np.array([[1, 2, 3], [4, 5, 6]]) 
array_b = np.array([[0, 1, 0], [1, 0, 1]]) 
array_a + array_b

array([[1, 3, 3],
       [5, 5, 7]])

Multiplicación de dos matrices 

In [13]:
array_a = np.array([[1, 2, 3], [4, 5, 6]]) 
array_b = np.array([[0, 1, 0], [1, 0, 1]]) 
array_a * array_b

array([[0, 2, 0],
       [4, 0, 6]])

Comparaciones

In [14]:
array = np.array([[1, 2, 3], [4, 5, 6]]) 
array > 2

array([[False, False,  True],
       [ True,  True,  True]])

Vectorizacion en Python

In [15]:
array = np.array(["NumPy", "is", "awesome"]) 
len(array) > 2

True

In [17]:
vectorized_len = np.vectorize(len)
vectorized_len(array) > 2

array([ True, False,  True])